base_url = "https://www.sigplan.org/cc"
compile_sass = true
build_search_index = false
title = "Current Continuation"
generate_feeds = true
author = "Aws Albarghouthi and Adrian Sampson"

[markdown]
highlight_code = true
smart_punctuation = true

[extra]
favicon = "favicon.ico"
logo = "img/sigplan-logo.png"
tagline = "a podcast from SIGPLAN about programming languages research"
audio_url = "http://sigplan-ccmedia.global.ssl.fastly.net/"
