base_url = "https://www.sigplan.org/cc"
compile_sass = true
build_search_index = false
title = "Current Continuation"
generate_feeds = true
feed_filenames = ["rss.xml"]
author = "Aws Albarghouthi and Adrian Sampson"
description = "a podcast from SIGPLAN about programming languages research"

[markdown]
highlight_code = true
smart_punctuation = true

[extra]
favicon = "favicon.ico"
logo = "img/sigplan-logo.png"
audio_url = "https://sigplan-ccmedia.global.ssl.fastly.net"
category = "Science"
email = "infodir_sigplan@acm.org"
