base_url = "https://www.sigplan.org/cc"
compile_sass = true
build_search_index = false
title = "Current Continuation"

[markdown]
highlight_code = true

[extra]
favicon = "favicon.ico"
bigicon = "favicon152.png"
tagline = "a podcast from SIGPLAN about programming languages research"
