on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Install Zola'
        run: sudo snap install --edge zola
      - name: 'Build Zola site'
        run: zola build --drafts
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: public
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{github.event_name=='push' && github.ref=='refs/heads/main'}}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: public
      - name: rsync
        if: ${{github.event_name=='push' && github.ref=='refs/heads/master'}}
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_KNOWN_HOSTS: ${{ secrets.DEPLOY_KNOWN_HOSTS }}
          DEPLOY_SRC: ./public/
          DEPLOY_DEST: public_html/pages/cc
        run: |
          echo "$DEPLOY_KEY" > pk
          echo "$DEPLOY_KNOWN_HOSTS" > kh
          chmod 600 pk
          rsync --compress --recursive --checksum --itemize-changes \
            -e "ssh -p \"$DEPLOY_PORT\" -i pk -o 'UserKnownHostsFile kh'" \
            $DEPLOY_SRC $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DEST
